name: MLflow Pipeline CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  mlflow_pipeline:
    runs-on: ubuntu-latest

    steps:
      # Stage 1: Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Stage 2: Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Stage 3: Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Stage 4: Run MLflow pipeline
      - name: Run Pipeline
        run: |
          python pipeline.py
          
      # Stage 5: Archive Artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: mlflow-artifacts
          path: |
            mlruns/
            model.joblib
            metrics.txt
